export const Factoids = {
  descriptors: [
    { id: 0, descriptor: 'choice' },
    { id: 1, descriptor: 'collectible' },
    { id: 2, descriptor: 'venerable' },
    { id: 3, descriptor: 'rare' },
    { id: 4, descriptor: 'mature' },
    { id: 5, descriptor: 'classical' },
    { id: 6, descriptor: 'uncommon' },
    { id: 7, descriptor: 'unique' },
    { id: 8, descriptor: 'unusual' },
    { id: 9, descriptor: 'extraordinary' },
    { id: 10, descriptor: 'artisanal' },
    { id: 11, descriptor: 'artisan' },
    { id: 12, descriptor: 'craft' },
    { id: 13, descriptor: 'hand-made' },
    { id: 14, descriptor: 'vintage' },
    { id: 15, descriptor: 'antique' },
    { id: 16, descriptor: 'reclaimed' }
  ],
  nouns: [
    { id: 0, noun: 'napkins' },
    { id: 1, noun: 'leaves' },
    { id: 2, noun: 'paper' },
    { id: 3, noun: 'styrofoam cups' },
    { id: 4, noun: 'paper plates' },
    { id: 5, noun: 'stamps' },
    { id: 6, noun: 'toilet paper' },
    { id: 7, noun: 'envelopes' },
    { id: 8, noun: 'party invitations' },
    { id: 9, noun: 'firecrackers' },
    { id: 10, noun: 'fireworks' },
    { id: 11, noun: 'piñatas' },
    { id: 12, noun: 'toast' },
    { id: 13, noun: 'cellophane' },
    { id: 14, noun: 'promises' },
    { id: 15, noun: 'rainbows' },
    { id: 16, noun: 'match sticks' },
    { id: 17, noun: 'bandages' },
    { id: 18, noun: 'dust bunnies' },
    { id: 19, noun: 'toothpicks' },
    { id: 20, noun: 'dental floss' },
    { id: 21, noun: 'gum wrappers' },
    { id: 22, noun: 'insults' },
    { id: 23, noun: 'puns' },
    { id: 24, noun: 'wreaths' },
    { id: 25, noun: 'disappointments' }
  ],
  verbs: [
    { id: 0, verb: 'repair' },
    { id: 1, verb: 'reassemble' },
    { id: 2, verb: 'remodel' },
    { id: 3, verb: 'refurbish' },
    { id: 4, verb: 'overhaul' },
    { id: 5, verb: 'repurposed' },
    { id: 6, verb: 'recycle' },
    { id: 7, verb: 'rehabilitate' },
    { id: 8, verb: 'refit' },
    { id: 9, verb: 'restore' },
    { id: 10, verb: 'modernize' },
    { id: 11, verb: 'retrofit' },
    { id: 12, verb: 'rejuvenate' },
    { id: 13, verb: 'recondition' }
  ]
};
